// supabase/functions/_shared/canonical_topology_v1.ts
//
// Single source of truth for the Phase 1C-B CanonicalTopologyCandidate
// contract (the CANDIDATE layer only -- RAW/AUDITED/PLAN types stay in
// Phase 1C-B's own model, see ../../../claude/phase1c-b/src/types/model.ts).
//
// This file mirrors phase1c-b-complete.zip's src/types/model.ts CANDIDATE
// layer EXACTLY -- field names, enum values, and canonical id formats are
// unchanged from the original, verified producer. Verified in session 25
// (CANONICAL TOPOLOGY CONTRACT AUDIT + FINAL CONTRACT VERIFICATION):
//   - read in full against the real phase1c-b-complete.zip source
//     (model.ts/construct.ts/validate.ts/fixtures/attempt3.ts),
//   - compiled and test-run (tsc --strict, 21/21 original tests),
//   - constructCanonicalTopology(attempt3Raw, attempt3ApprovedPlan, ...)
//     re-executed independently and diffed byte-for-byte against
//     attempt3-actual-candidate.json -- identical.
//
// Do NOT simplify this for any one consumer's needs. Phase 1C-B (the
// producer), Phase 2-B Part A, and Phase 2-B Part B all import this same
// file -- a consumer that only needs a subset of these fields reads what it
// needs from the full shape; it must never re-declare a narrower
// CanonicalVertex/CanonicalEdge/CanonicalTopologyCandidate of its own.
//
// canonicalEdgeId is ALWAYS `canon-${sourceRawEdgeId}` -- this is the real,
// production id format generated by constructCanonicalTopology itself, not
// a convenience convention for any one consumer. Never strip this prefix in
// a shared type or fixture.

export type SemanticConfidence = 'HIGH' | 'MEDIUM_HIGH' | 'MEDIUM' | 'LOW';

export type GeometryAlignmentStatus =
  | 'NOT_AUDITED'
  | 'ALIGNED'
  | 'NEAR'
  | 'MISALIGNED'
  | 'UNRESOLVED';

export type CoordinateStatus =
  | 'RAW_OBSERVATION'
  | 'MISALIGNED'
  | 'UNRESOLVED'
  | 'CONSTRAINT_SOLVED';

export type SemanticVerificationScope =
  | 'FULL_SPAN'
  | 'VISIBLE_SPAN'
  | 'LOCAL_ADJACENCY_CONFIRMED';

export type CanonicalGapType =
  | 'OPENING_CONTINUATION_UNKNOWN'
  | 'SOURCE_OCCLUDED'
  | 'UNSUPPORTED_BOUNDARY_RELATION';

export type DeferredIssueType =
  | 'TOPOLOGY_REPAIR_REQUIRED'
  | 'GEOMETRY_REALIGNMENT_REQUIRED'
  | 'UNCONFIRMED_BOUNDARY_CANDIDATE';

export type CandidateState =
  | 'CLOSED_CONFIRMED'
  | 'OPEN_WITH_GAPS'
  | 'OPEN_WITH_DEFERRED_REPAIR'
  | 'INVALID';

export type ValidationRuleName =
  | 'NO_UNPROVEN_EDGE'
  | 'NO_RAW_MUTATION'
  | 'NO_PROXIMITY_ONLY_REPAIR'
  | 'NO_FORCED_CLOSURE'
  | 'PROVENANCE_COMPLETE'
  | 'NO_REJECTED_EDGE_ACTIVE'
  | 'GAPS_EXPLICIT'
  | 'DEFERRED_ISSUES_PRESERVED'
  | 'CANONICAL_FACE_SELECTION_RESPECTED'
  | 'GRAPH_STRUCTURALLY_VALID'
  | 'DEFERRED_DOES_NOT_IMPLY_EXCLUSION'
  | 'NO_ORPHAN_EDGE_ENDPOINTS'
  | 'CONNECTED_COMPONENTS_EDGE_INDUCED'
  | 'SINGLE_CANONICAL_EDGE_OWNER';

export interface CanonicalVertex {
  readonly canonicalVertexId: string;
  readonly sourceRawVertexIds: readonly string[];
  readonly coordinate: { readonly x: number; readonly y: number };
  readonly coordinateStatus: CoordinateStatus;
  readonly coordinateEvidenceRef: string;
  readonly provenanceNote: string;
}

export interface CanonicalEdge {
  readonly canonicalEdgeId: string; // ALWAYS "canon-" + source RAW edge id
  readonly sourceRawEdgeIds: readonly string[];
  readonly fromCanonicalVertexId: string;
  readonly toCanonicalVertexId: string;
  readonly originatingOperationId: string;
  readonly semanticStatus: 'KEEP_ENVELOPE'; // only value ever assigned here
  readonly semanticConfidence: SemanticConfidence;
  readonly semanticVerificationScope: SemanticVerificationScope;
  readonly geometryVerificationStatus: GeometryAlignmentStatus;
  readonly unverifiedPortion: string | null;
  readonly provenanceNote: string;
}

export interface CanonicalGap {
  readonly gapId: string;
  readonly gapType: CanonicalGapType;
  readonly knownEndpointVertexIds: readonly string[];
  readonly unknownEndpointCount: number;
  readonly reason: string;
  readonly evidenceRefs: readonly string[];
  readonly resolutionStatus: 'UNRESOLVED';
  readonly deferTo: string;
  readonly originatingOperationId: string;
}

export interface DeferredIssue {
  readonly issueId: string;
  readonly relatedOperationId: string;
  readonly issueType: DeferredIssueType;
  readonly affectedRawVertices: readonly string[];
  readonly affectedRawEdges: readonly string[];
  readonly evidenceRefs: readonly string[];
  readonly resolutionConfidence: 'NONE';
  readonly deferTo: string;
  readonly provenanceNote: string;
}

export interface ConnectedComponent {
  readonly componentId: string;
  readonly vertexIds: readonly string[];
  readonly edgeIds: readonly string[];
}

export interface ValidationResult {
  readonly rule: ValidationRuleName;
  readonly passed: boolean;
  readonly details: string;
}

export interface StateFlags {
  readonly hasExplicitGaps: boolean;
  readonly hasDeferredRepairs: boolean;
  readonly hasUnverifiedPartialEdges: boolean;
  readonly isFullyClosed: boolean;
}

export interface CanonicalTopologyCandidate {
  readonly candidateId: string;
  readonly vertices: readonly CanonicalVertex[];
  readonly edges: readonly CanonicalEdge[];
  readonly gaps: readonly CanonicalGap[];
  readonly deferredIssues: readonly DeferredIssue[];
  readonly connectedComponents: readonly ConnectedComponent[];
  readonly validationResults: readonly ValidationResult[];
  readonly stateFlags: StateFlags;
  readonly candidateState: CandidateState;
}

// ---- Lookup helpers -------------------------------------------------------
// Pure, read-only lookups against a specific CanonicalTopologyCandidate
// instance. This is the ONLY way anchor validation may confirm existence --
// per RAW_EXISTENCE_DOES_NOT_IMPLY_CANONICAL_EXISTENCE, a RAW or AUDITED-only
// id must never satisfy these. Generalized from Phase 2-B Part A's original
// topology-input.ts helpers (session 25 migration) -- field names updated to
// match this shared contract; behavior unchanged.

export function canonicalVertexExists(
  candidate: CanonicalTopologyCandidate,
  vertexId: string,
): boolean {
  return candidate.vertices.some((v) => v.canonicalVertexId === vertexId);
}

export function findCanonicalEdge(
  candidate: CanonicalTopologyCandidate,
  edgeId: string,
): CanonicalEdge | undefined {
  return candidate.edges.find((e) => e.canonicalEdgeId === edgeId);
}

export function canonicalEdgeExists(
  candidate: CanonicalTopologyCandidate,
  edgeId: string,
): boolean {
  return findCanonicalEdge(candidate, edgeId) !== undefined;
}

export function canonicalGapExists(
  candidate: CanonicalTopologyCandidate,
  gapId: string,
): boolean {
  return candidate.gaps.some((g) => g.gapId === gapId);
}

export function canonicalDeferredIssueExists(
  candidate: CanonicalTopologyCandidate,
  issueId: string,
): boolean {
  return candidate.deferredIssues.some((d) => d.issueId === issueId);
}
