#!/bin/bash
set -e
cd /workspaces/shift-app/shift_app

cat > assets/translations/he.json << 'SHIFTEOF_HE'
{
  "home": {
    "title": "SHIFT",
    "connected": "מחובר בהצלחה ל-Supabase",
    "not_connected": "אין חיבור לשרת",
    "placeholder_note": "שלד פרויקט (שלב 2) — מסכי האפליקציה האמיתיים יתווספו בשלבים הבאים"
  },
  "home_screen": {
    "app_title": "SHIFT",
    "title": "מה מעצבים היום?",
    "subtitle": "בחר את סוג החדר ומה תרצה לשנות בו",
    "room_section": "סוג החדר",
    "groups_section": "מה תרצה לעצב?",
    "select_room_first": "קודם בוחרים סוג חדר",
    "continue_button": "המשך לבחירת חומרים",
    "credits_free": "{} הדמיות חינם נותרו",
    "credits_subscription": "מנוי פעיל — {} הדמיות נותרו החודש",
    "credits_exhausted": "המכסה נגמרה"
  },
  "design_studio_screen": {
    "app_title": "SHIFT",
    "title": "בחירת חומרים",
    "no_items": "אין פריטים זמינים בקטגוריה הזו לסוג החדר שנבחר",
    "continue_button": "המשך להעלאת תמונה",
    "note_hint": "הוסף הערה חופשית לבחירה הזו (רשות)",
    "note_field_hint": "לדוגמה: רק על קיר אחד, לא בכל החדר",
    "note_save": "שמירה"
  },
  "upload_photo_screen": {
    "app_title": "SHIFT",
    "title": "העלה תמונה שתרצה לעצב",
    "subtitle": "כדי שנוכל להראות לך איך זה נראה אצלך",
    "shift_button": "SHIFT",
    "eta_note": "יצירת ההדמיה תיקח עד כ-20 שניות",
    "take_photo": "צלם תמונה",
    "choose_gallery": "בחר מהגלריה",
    "tap_to_pick": "גע כדי לצלם או לבחור מהגלריה",
    "uploaded_ok": "התמונה הועלתה בהצלחה",
    "file_hint": "JPG · PNG · עד 15MB"
  },
  "processing_screen": {
    "app_title": "SHIFT",
    "title": "יוצרים את ההדמיה שלך",
    "eta_note": "לוקח בדרך כלל עד כ-20 שניות",
    "leave_ok_note": "אפשר לצאת מהמסך בלי חשש — ההדמיה תמשיך ברקע, ותופיע כאן ובגלריה שלך ברגע שתהיה מוכנה.",
    "resuming_note": "ההדמיה הקודמת שלך עדיין הייתה בעיבוד — ממשיכים לעקוב אחריה בדיוק מאיפה שהפסקנו.",
    "still_working_title": "עדיין עובדים על זה",
    "still_working_body": "זה לוקח קצת יותר זמן מהרגיל, אבל שום דבר לא אבד. אפשר לחזור למסך הבית — ההדמיה תופיע שם אוטומטית ברגע שתהיה מוכנה, וגם בגלריה שלך.",
    "still_working_wait_button": "להמשיך להמתין",
    "quota_title": "נגמרה המכסה",
    "quota_body": "אין לך כרגע הדמיות זמינות. אפשר לשדרג למנוי כדי להמשיך.",
    "quota_button": "חזרה למסך הבית",
    "error_title": "משהו השתבש",
    "retry_button": "נסה שוב",
    "back_button": "חזרה"
  },
  "result_screen": {
    "app_title": "SHIFT",
    "title": "ההדמיה שלך מוכנה!",
    "before_label": "לפני",
    "after_label": "אחרי",
    "save_button": "שמירה ב-HD",
    "share_button": "שיתוף בוואטסאפ",
    "design_again_button": "עיצוב נוסף לחדר הזה",
    "view_gallery_button": "לצפייה בכל ההדמיות שלי",
    "image_error": "לא הצלחנו לטעון את התמונה",
    "retry_button": "נסה שוב",
    "share_error": "לא הצלחנו לשתף את התמונה",
    "rating_title": "איך היה?",
    "rating_hint": "ספר לנו עוד (רשות)",
    "rating_submit": "שליחה",
    "rating_thanks": "תודה על המשוב!",
    "milestone_q1": "מה דעתך על האפליקציה והשימוש שלך עד כה?",
    "milestone_very_good": "טוב מאוד",
    "milestone_ok": "בסדר",
    "milestone_not_great": "לא משהו",
    "milestone_q2": "האם היו חסרים לך אלמנטים מסוימים?",
    "milestone_yes": "כן",
    "milestone_no": "לא",
    "milestone_missing_hint": "נשמח לעדכן את המערכת — מה חסר לך?",
    "milestone_send": "שליחה"
  },
  "coupon_screen": {
    "app_title": "קוד קופון",
    "title": "יש לך קוד קופון?",
    "subtitle": "הזן את הקוד שקיבלת ותראה מיד אם הוא בתוקף",
    "field_hint": "לדוגמה: DANI-GIFT-1M",
    "redeem_button": "מימוש הקוד",
    "success_granted_title": "מזל טוב!",
    "success_granted_body": "הקוד מומש בהצלחה. המנוי שלך ({}) בתוקף עד {}.",
    "success_tracked": "הקוד נרשם בהצלחה, תודה!",
    "error_not_found": "קוד קופון לא נמצא. בדוק שהקלדת נכון ונסה שוב.",
    "error_inactive": "קוד הקופון הזה כבר לא פעיל.",
    "error_expired": "תוקף הקוד הזה פג.",
    "error_limit": "הקוד הזה כבר מוצה במלואו.",
    "error_already_redeemed": "כבר מימשת את הקוד הזה בעבר.",
    "error_generic": "קרה משהו לא צפוי. אפשר לנסות שוב.",
    "tier_monthly": "חודשי",
    "tier_annual": "שנתי",
    "tier_annual_premium": "שנתי פרימיום",
    "entry_tooltip": "יש לי קוד קופון"
  },
  "gallery_screen": {
    "app_title": "הגלריה שלי",
    "entry_tooltip": "הגלריה שלי",
    "empty_title": "עדיין אין כאן כלום",
    "empty_body": "כל הדמיה שתיצור תישמר כאן אוטומטית, כדי שתוכל לחזור אליה בכל זמן.",
    "load_error": "לא הצלחנו לטעון את הגלריה",
    "retry_button": "נסה שוב",
    "share_button": "שיתוף",
    "delete_button": "מחיקה",
    "delete_confirm_title": "למחוק את התמונה?",
    "delete_confirm_body": "הפעולה לא הפיכה — התמונה תימחק לצמיתות מהגלריה שלך.",
    "delete_confirm_yes": "מחיקה",
    "delete_confirm_cancel": "ביטול",
    "delete_error": "המחיקה נכשלה, נסה שוב"
  },
  "language": {
    "select": "בחר שפה",
    "he": "עברית",
    "ar": "ערבית",
    "ru": "רוסית",
    "en": "אנגלית"
  }
}
SHIFTEOF_HE

cat > assets/translations/en.json << 'SHIFTEOF_EN'
{
  "home": {
    "title": "SHIFT",
    "connected": "Connected to Supabase successfully",
    "not_connected": "No connection to the server",
    "placeholder_note": "Project scaffold (stage 2) — real app screens will be added in later stages"
  },
  "home_screen": {
    "app_title": "SHIFT",
    "title": "What are we designing today?",
    "subtitle": "Choose the room type and what you'd like to change",
    "room_section": "Room type",
    "groups_section": "What would you like to design?",
    "select_room_first": "Choose a room type first",
    "continue_button": "Continue to materials",
    "credits_free": "{} free renders left",
    "credits_subscription": "Active subscription — {} renders left this month",
    "credits_exhausted": "You've used your quota"
  },
  "design_studio_screen": {
    "app_title": "SHIFT",
    "title": "Choose materials",
    "no_items": "No items available in this category for the selected room",
    "continue_button": "Continue to upload photo",
    "note_hint": "Add an optional note for this choice",
    "note_field_hint": "e.g. only on one wall, not the whole room",
    "note_save": "Save"
  },
  "upload_photo_screen": {
    "app_title": "SHIFT",
    "title": "Upload a photo to design",
    "subtitle": "So we can show you what it looks like at your place",
    "shift_button": "SHIFT",
    "eta_note": "Creating the render takes up to about 20 seconds",
    "take_photo": "Take a photo",
    "choose_gallery": "Choose from gallery",
    "tap_to_pick": "Tap to take a photo or choose from gallery",
    "uploaded_ok": "Photo uploaded successfully",
    "file_hint": "JPG · PNG · up to 15MB"
  },
  "processing_screen": {
    "app_title": "SHIFT",
    "title": "Creating your render",
    "eta_note": "Usually takes up to about 20 seconds",
    "leave_ok_note": "It's fine to leave this screen — your render keeps going in the background, and will show up here and in your gallery as soon as it's ready.",
    "resuming_note": "Your previous render was still processing — picking up right where we left off.",
    "still_working_title": "Still working on it",
    "still_working_body": "This is taking a bit longer than usual, but nothing was lost. You can go back to the home screen — your render will appear there automatically once it's ready, and in your gallery too.",
    "still_working_wait_button": "Keep waiting",
    "quota_title": "You've used your quota",
    "quota_body": "You don't have any renders available right now. You can upgrade to a subscription to continue.",
    "quota_button": "Back to home",
    "error_title": "Something went wrong",
    "retry_button": "Try again",
    "back_button": "Back"
  },
  "result_screen": {
    "app_title": "SHIFT",
    "title": "Your design is ready!",
    "before_label": "Before",
    "after_label": "After",
    "save_button": "Save HD",
    "share_button": "Share on WhatsApp",
    "design_again_button": "Design another for this room",
    "view_gallery_button": "View all my renders",
    "image_error": "We couldn't load the image",
    "retry_button": "Try again",
    "share_error": "We couldn't share the image",
    "rating_title": "How was it?",
    "rating_hint": "Tell us more (optional)",
    "rating_submit": "Submit",
    "rating_thanks": "Thanks for the feedback!",
    "milestone_q1": "What do you think of the app and your experience so far?",
    "milestone_very_good": "Very good",
    "milestone_ok": "OK",
    "milestone_not_great": "Not great",
    "milestone_q2": "Was anything missing?",
    "milestone_yes": "Yes",
    "milestone_no": "No",
    "milestone_missing_hint": "We'd love to know — what's missing?",
    "milestone_send": "Send"
  },
  "coupon_screen": {
    "app_title": "Coupon Code",
    "title": "Have a coupon code?",
    "subtitle": "Enter your code below to see if it's valid",
    "field_hint": "e.g. DANI-GIFT-1M",
    "redeem_button": "Redeem code",
    "success_granted_title": "Congratulations!",
    "success_granted_body": "Your code was redeemed successfully. Your {} subscription is active until {}.",
    "success_tracked": "Your code was recorded — thank you!",
    "error_not_found": "Coupon code not found. Check the spelling and try again.",
    "error_inactive": "This coupon code is no longer active.",
    "error_expired": "This coupon code has expired.",
    "error_limit": "This coupon code has already been fully used.",
    "error_already_redeemed": "You've already redeemed this code.",
    "error_generic": "Something went wrong. Please try again.",
    "tier_monthly": "Monthly",
    "tier_annual": "Annual",
    "tier_annual_premium": "Annual Premium",
    "entry_tooltip": "I have a coupon code"
  },
  "gallery_screen": {
    "app_title": "My Gallery",
    "entry_tooltip": "My gallery",
    "empty_title": "Nothing here yet",
    "empty_body": "Every render you create is saved here automatically, so you can come back to it anytime.",
    "load_error": "We couldn't load your gallery",
    "retry_button": "Try again",
    "share_button": "Share",
    "delete_button": "Delete",
    "delete_confirm_title": "Delete this image?",
    "delete_confirm_body": "This can't be undone — the image will be permanently deleted from your gallery.",
    "delete_confirm_yes": "Delete",
    "delete_confirm_cancel": "Cancel",
    "delete_error": "Delete failed, please try again"
  },
  "language": {
    "select": "Select language",
    "he": "Hebrew",
    "ar": "Arabic",
    "ru": "Russian",
    "en": "English"
  }
}
SHIFTEOF_EN

cat > assets/translations/ru.json << 'SHIFTEOF_RU'
{
  "home": {
    "title": "SHIFT",
    "connected": "Успешно подключено к Supabase",
    "not_connected": "Нет подключения к серверу",
    "placeholder_note": "Каркас проекта (этап 2) — реальные экраны приложения будут добавлены на следующих этапах"
  },
  "home_screen": {
    "app_title": "SHIFT",
    "title": "Что оформляем сегодня?",
    "subtitle": "Выберите тип комнаты и что хотите изменить",
    "room_section": "Тип комнаты",
    "groups_section": "Что вы хотите изменить?",
    "select_room_first": "Сначала выберите тип комнаты",
    "continue_button": "Далее к выбору материалов",
    "credits_free": "Осталось бесплатных рендеров: {}",
    "credits_subscription": "Активная подписка — осталось {} в этом месяце",
    "credits_exhausted": "Лимит исчерпан"
  },
  "design_studio_screen": {
    "app_title": "SHIFT",
    "title": "Выбор материалов",
    "no_items": "Нет доступных вариантов в этой категории для выбранной комнаты",
    "continue_button": "Далее к загрузке фото",
    "note_hint": "Добавьте необязательное примечание к этому выбору",
    "note_field_hint": "например: только на одной стене, не по всей комнате",
    "note_save": "Сохранить"
  },
  "upload_photo_screen": {
    "app_title": "SHIFT",
    "title": "Загрузите фото для дизайна",
    "subtitle": "Чтобы мы могли показать, как это будет выглядеть у вас",
    "shift_button": "SHIFT",
    "eta_note": "Создание рендера может занять до 20 секунд",
    "take_photo": "Сделать фото",
    "choose_gallery": "Выбрать из галереи",
    "tap_to_pick": "Нажмите, чтобы сделать фото или выбрать из галереи",
    "uploaded_ok": "Фото успешно загружено",
    "file_hint": "JPG · PNG · до 15МБ"
  },
  "processing_screen": {
    "app_title": "SHIFT",
    "title": "Создаём ваш рендер",
    "eta_note": "Обычно занимает до 20 секунд",
    "leave_ok_note": "Можно спокойно покинуть этот экран — рендер продолжит создаваться в фоне и появится здесь и в вашей галерее, как только будет готов.",
    "resuming_note": "Ваш предыдущий рендер всё ещё обрабатывался — продолжаем следить за ним с того же места.",
    "still_working_title": "Всё ещё работаем над этим",
    "still_working_body": "Это занимает немного больше времени, чем обычно, но ничего не потеряно. Можно вернуться на главный экран — рендер появится там автоматически, как только будет готов, а также в вашей галерее.",
    "still_working_wait_button": "Продолжить ждать",
    "quota_title": "Лимит исчерпан",
    "quota_body": "Сейчас у вас нет доступных рендеров. Вы можете оформить подписку, чтобы продолжить.",
    "quota_button": "На главный экран",
    "error_title": "Что-то пошло не так",
    "retry_button": "Попробовать снова",
    "back_button": "Назад"
  },
  "result_screen": {
    "app_title": "SHIFT",
    "title": "Ваш дизайн готов!",
    "before_label": "До",
    "after_label": "После",
    "save_button": "Сохранить в HD",
    "share_button": "Поделиться в WhatsApp",
    "design_again_button": "Ещё один дизайн для этой комнаты",
    "view_gallery_button": "Смотреть все мои рендеры",
    "image_error": "Не удалось загрузить изображение",
    "retry_button": "Попробовать снова",
    "share_error": "Не удалось поделиться изображением",
    "rating_title": "Как вам?",
    "rating_hint": "Расскажите подробнее (необязательно)",
    "rating_submit": "Отправить",
    "rating_thanks": "Спасибо за отзыв!",
    "milestone_q1": "Что вы думаете о приложении и своём опыте использования?",
    "milestone_very_good": "Очень хорошо",
    "milestone_ok": "Нормально",
    "milestone_not_great": "Не очень",
    "milestone_q2": "Чего-то не хватало?",
    "milestone_yes": "Да",
    "milestone_no": "Нет",
    "milestone_missing_hint": "Мы хотим улучшить систему — чего вам не хватает?",
    "milestone_send": "Отправить"
  },
  "coupon_screen": {
    "app_title": "Промокод",
    "title": "Есть промокод?",
    "subtitle": "Введите код, чтобы проверить, действителен ли он",
    "field_hint": "Например: DANI-GIFT-1M",
    "redeem_button": "Активировать код",
    "success_granted_title": "Поздравляем!",
    "success_granted_body": "Код успешно активирован. Ваша подписка ({}) действует до {}.",
    "success_tracked": "Код успешно зарегистрирован, спасибо!",
    "error_not_found": "Промокод не найден. Проверьте правильность ввода и попробуйте снова.",
    "error_inactive": "Этот промокод больше не активен.",
    "error_expired": "Срок действия этого кода истёк.",
    "error_limit": "Этот код уже полностью использован.",
    "error_already_redeemed": "Вы уже использовали этот код.",
    "error_generic": "Произошла непредвиденная ошибка. Попробуйте снова.",
    "tier_monthly": "Ежемесячная",
    "tier_annual": "Годовая",
    "tier_annual_premium": "Годовая Премиум",
    "entry_tooltip": "У меня есть промокод"
  },
  "gallery_screen": {
    "app_title": "Моя галерея",
    "entry_tooltip": "Моя галерея",
    "empty_title": "Здесь пока пусто",
    "empty_body": "Каждый созданный вами рендер сохраняется здесь автоматически, чтобы вы могли вернуться к нему в любое время.",
    "load_error": "Не удалось загрузить галерею",
    "retry_button": "Попробовать снова",
    "share_button": "Поделиться",
    "delete_button": "Удалить",
    "delete_confirm_title": "Удалить это изображение?",
    "delete_confirm_body": "Это действие необратимо — изображение будет удалено из вашей галереи навсегда.",
    "delete_confirm_yes": "Удалить",
    "delete_confirm_cancel": "Отмена",
    "delete_error": "Не удалось удалить, попробуйте снова"
  },
  "language": {
    "select": "Выберите язык",
    "he": "Иврит",
    "ar": "Арабский",
    "ru": "Русский",
    "en": "Английский"
  }
}
SHIFTEOF_RU

cat > assets/translations/ar.json << 'SHIFTEOF_AR'
{
  "home": {
    "title": "SHIFT",
    "connected": "تم الاتصال بنجاح بـ Supabase",
    "not_connected": "لا يوجد اتصال بالخادم",
    "placeholder_note": "هيكل المشروع (المرحلة 2) — سيتم إضافة شاشات التطبيق الفعلية في المراحل القادمة"
  },
  "home_screen": {
    "app_title": "SHIFT",
    "title": "ماذا نصمم اليوم؟",
    "subtitle": "اختر نوع الغرفة وما تريد تغييره فيها",
    "room_section": "نوع الغرفة",
    "groups_section": "ماذا تريد أن تصمم؟",
    "select_room_first": "اختر نوع الغرفة أولاً",
    "continue_button": "متابعة لاختيار المواد",
    "credits_free": "{} صور مجانية متبقية",
    "credits_subscription": "اشتراك نشط — {} صور متبقية هذا الشهر",
    "credits_exhausted": "لقد استنفدت حصتك"
  },
  "design_studio_screen": {
    "app_title": "SHIFT",
    "title": "اختيار المواد",
    "no_items": "لا توجد عناصر متاحة في هذه الفئة لنوع الغرفة المختار",
    "continue_button": "متابعة لرفع الصورة",
    "note_hint": "أضف ملاحظة اختيارية لهذا الاختيار",
    "note_field_hint": "مثال: فقط على جدار واحد، وليس الغرفة كلها",
    "note_save": "حفظ"
  },
  "upload_photo_screen": {
    "app_title": "SHIFT",
    "title": "ارفع صورة تريد تصميمها",
    "subtitle": "حتى نتمكن من إظهار كيف سيبدو الأمر عندك",
    "shift_button": "SHIFT",
    "eta_note": "إنشاء الصورة قد يستغرق حتى 20 ثانية",
    "take_photo": "التقط صورة",
    "choose_gallery": "اختر من المعرض",
    "tap_to_pick": "اضغط لالتقاط صورة أو الاختيار من المعرض",
    "uploaded_ok": "تم رفع الصورة بنجاح",
    "file_hint": "JPG · PNG · حتى 15 ميغابايت"
  },
  "processing_screen": {
    "app_title": "SHIFT",
    "title": "جارٍ إنشاء التصميم الخاص بك",
    "eta_note": "يستغرق عادةً حتى 20 ثانية",
    "leave_ok_note": "يمكنك مغادرة هذه الشاشة بلا قلق — التصميم يستمر في الخلفية، وسيظهر هنا وفي معرضك بمجرد أن يكون جاهزاً.",
    "resuming_note": "تصميمك السابق كان لا يزال قيد المعالجة — نواصل متابعته من حيث توقفنا بالضبط.",
    "still_working_title": "لا زلنا نعمل على ذلك",
    "still_working_body": "هذا يستغرق وقتاً أطول قليلاً من المعتاد، لكن لم يُفقد شيء. يمكنك العودة للشاشة الرئيسية — سيظهر التصميم هناك تلقائياً بمجرد جاهزيته، وأيضاً في معرضك.",
    "still_working_wait_button": "الاستمرار بالانتظار",
    "quota_title": "لقد استنفدت حصتك",
    "quota_body": "لا توجد لديك صور متاحة حالياً. يمكنك الترقية إلى اشتراك للمتابعة.",
    "quota_button": "العودة للشاشة الرئيسية",
    "error_title": "حدث خطأ ما",
    "retry_button": "حاول مرة أخرى",
    "back_button": "رجوع"
  },
  "result_screen": {
    "app_title": "SHIFT",
    "title": "تصميمك جاهز!",
    "before_label": "قبل",
    "after_label": "بعد",
    "save_button": "حفظ بجودة HD",
    "share_button": "مشاركة عبر واتساب",
    "design_again_button": "تصميم آخر لهذه الغرفة",
    "view_gallery_button": "عرض كل تصاميمي",
    "image_error": "تعذّر تحميل الصورة",
    "retry_button": "حاول مرة أخرى",
    "share_error": "تعذّرت مشاركة الصورة",
    "rating_title": "كيف كانت التجربة؟",
    "rating_hint": "أخبرنا المزيد (اختياري)",
    "rating_submit": "إرسال",
    "rating_thanks": "شكراً على ملاحظاتك!",
    "milestone_q1": "ما رأيك في التطبيق وتجربتك حتى الآن؟",
    "milestone_very_good": "جيد جداً",
    "milestone_ok": "جيد",
    "milestone_not_great": "ليس رائعاً",
    "milestone_q2": "هل كان هناك عناصر ناقصة؟",
    "milestone_yes": "نعم",
    "milestone_no": "لا",
    "milestone_missing_hint": "يسعدنا تحديث النظام — ما الذي ينقصك؟",
    "milestone_send": "إرسال"
  },
  "coupon_screen": {
    "app_title": "رمز الكوبون",
    "title": "هل لديك رمز كوبون؟",
    "subtitle": "أدخل الرمز الذي حصلت عليه لترى إذا كان صالحاً",
    "field_hint": "مثال: DANI-GIFT-1M",
    "redeem_button": "استخدام الرمز",
    "success_granted_title": "مبروك!",
    "success_granted_body": "تم استخدام الرمز بنجاح. اشتراكك ({}) ساري حتى {}.",
    "success_tracked": "تم تسجيل الرمز بنجاح، شكراً لك!",
    "error_not_found": "رمز الكوبون غير موجود. تحقق من الإدخال وحاول مرة أخرى.",
    "error_inactive": "رمز الكوبون هذا لم يعد نشطاً.",
    "error_expired": "انتهت صلاحية هذا الرمز.",
    "error_limit": "تم استخدام هذا الرمز بالكامل بالفعل.",
    "error_already_redeemed": "لقد استخدمت هذا الرمز من قبل.",
    "error_generic": "حدث خطأ غير متوقع. حاول مرة أخرى.",
    "tier_monthly": "شهري",
    "tier_annual": "سنوي",
    "tier_annual_premium": "سنوي مميز",
    "entry_tooltip": "لدي رمز كوبون"
  },
  "gallery_screen": {
    "app_title": "معرضي",
    "entry_tooltip": "معرضي",
    "empty_title": "لا يوجد شيء هنا بعد",
    "empty_body": "كل تصميم تنشئه يُحفظ هنا تلقائياً، حتى تتمكن من العودة إليه في أي وقت.",
    "load_error": "تعذّر تحميل المعرض",
    "retry_button": "حاول مرة أخرى",
    "share_button": "مشاركة",
    "delete_button": "حذف",
    "delete_confirm_title": "حذف هذه الصورة؟",
    "delete_confirm_body": "لا يمكن التراجع عن هذا — ستُحذف الصورة نهائياً من معرضك.",
    "delete_confirm_yes": "حذف",
    "delete_confirm_cancel": "إلغاء",
    "delete_error": "فشل الحذف، حاول مرة أخرى"
  },
  "language": {
    "select": "اختر اللغة",
    "he": "العبرية",
    "ar": "العربية",
    "ru": "الروسية",
    "en": "الإنجليزية"
  }
}
SHIFTEOF_AR

echo "✅ 4 קבצי התרגום עודכנו (30 → 20 שניות)."
