-- SHIFT — initial Supabase schema (stage 2 of the roadmap)
-- Run this once in: Supabase Dashboard -> SQL Editor -> New query -> paste -> Run
-- (or via `supabase db push` if you use the Supabase CLI locally).
--
-- Covers only what stage 2 needs: user profiles (credits/subscription state),
-- render history, and image storage — with Row Level Security so each user
-- can only ever see/modify their own data. No payment/paywall UI logic here
-- (that's stage 6) — this just gives it a place to read/write to.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- profiles: one row per auth user. Tracks freemium usage and subscription
-- state (values match the pricing spec: free / monthly / annual / annual_premium).
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text,
  free_credits_used integer not null default 0,
  subscription_tier text not null default 'free'
    check (subscription_tier in ('free', 'monthly', 'annual', 'annual_premium')),
  subscription_expires_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

create policy "Users can view their own profile"
  on public.profiles for select
  using (auth.uid() = id);

create policy "Users can update their own profile"
  on public.profiles for update
  using (auth.uid() = id);

-- Auto-create a profile row the moment a new auth user signs up.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ---------------------------------------------------------------------------
-- renders: history of AI visualizations generated by each user.
-- style_selections stores the chosen dictionary entries (id/label_he/prompt_en
-- per the schema agreed for the materials dictionary) as JSON, so the exact
-- prompt that produced a given render can always be reconstructed.
-- ---------------------------------------------------------------------------
create table if not exists public.renders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  category text, -- 'interior' | 'exterior' (per PRD's two project types)
  before_image_path text,
  after_image_path text,
  style_selections jsonb,
  created_at timestamptz not null default now()
);

alter table public.renders enable row level security;

create policy "Users can view their own renders"
  on public.renders for select
  using (auth.uid() = user_id);

create policy "Users can insert their own renders"
  on public.renders for insert
  with check (auth.uid() = user_id);

create policy "Users can delete their own renders"
  on public.renders for delete
  using (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- Storage: a private bucket for before/after images, one folder per user
-- (path convention: "<user_id>/...") enforced by the policies below.
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('renders', 'renders', false)
on conflict (id) do nothing;

create policy "Users can read their own render images"
  on storage.objects for select
  using (bucket_id = 'renders' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "Users can upload their own render images"
  on storage.objects for insert
  with check (bucket_id = 'renders' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "Users can delete their own render images"
  on storage.objects for delete
  using (bucket_id = 'renders' and (storage.foldername(name))[1] = auth.uid()::text);

-- ---------------------------------------------------------------------------
-- Account & data deletion (required by Apple/Google — spec doc on legal/privacy).
-- This RPC lets a signed-in user permanently delete all their app data in one
-- call from the client (Settings -> "Delete account & data").
--
-- NOTE: this deletes the user's application data (renders, storage objects,
-- profile) but NOT the auth.users row itself — deleting an auth user requires
-- the service_role key (admin privileges), which must never be embedded in
-- the client app. Fully removing the auth account needs a Supabase Edge
-- Function (server-side, holding the service_role key as a secret) that
-- calls this RPC and then the Supabase Admin API. That Edge Function is
-- built in the relevant later stage — flagging it here so it isn't forgotten.
-- ---------------------------------------------------------------------------
create or replace function public.delete_own_account_data()
returns void
language plpgsql
security definer set search_path = public
as $$
declare
  uid uuid := auth.uid();
begin
  if uid is null then
    raise exception 'Not authenticated';
  end if;

  delete from storage.objects
    where bucket_id = 'renders' and (storage.foldername(name))[1] = uid::text;

  delete from public.renders where user_id = uid;
  delete from public.profiles where id = uid;
end;
$$;
